[package]
name = "penumbra-reindexer"
authors = ["Penumbra Labs <team@penumbralabs.xyz"]
description = "A reindexing tool for Penumbra ABCI event data"
homepage = "https://penumbra.zone"
repository = "https://github.com/penumbra-zone/reindexer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
async-trait = "0.1.81"
clap = { version = "4", features = ["derive"] }
directories = "5.0.1"
ibc-types = "0.12.0"
penumbra-proto = { git = "https://github.com/penumbra-zone/penumbra", tag = "v0.80.2", features = ["tendermint"] } 
tendermint = { version = "0.34.0", default-features = false }
tendermint-proto = { version = "0.34.0", default-features = false }
serde_json = "1.0.125"
sqlx = { version = "0.8.0", features = ["runtime-tokio", "sqlite", "postgres"] }
tokio = { version = "1.39.3", features = ["rt"] }
toml = "0.8.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
# V0.79 dependencies
cnidarium-v0o79 = { package = "cnidarium", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events-backport" } 
penumbra-app-v0o79 = { package = "penumbra-app", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events-backport" } 
penumbra-ibc-v0o79 = { package = "penumbra-ibc", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events-backport" } 
# V0.80 dependencies
cnidarium-v0o80 = { package = "cnidarium", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
penumbra-app-v0o80 = { package = "penumbra-app", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
penumbra-governance-v0o80 = { package = "penumbra-governance", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
penumbra-ibc-v0o80 = { package = "penumbra-ibc", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
penumbra-transaction-v0o80 = { package = "penumbra-transaction", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
penumbra-sct-v0o80 = { package = "penumbra-sct", git = "https://github.com/penumbra-zone/penumbra", branch = "transfer-events" } 
hex = "0.4.3"


# In debug builds, nonetheless compile dependencies in release mode, for performance.
#
# The penumbra deps in particular are quit slow in debug mode, but this lets us iterate
# on the code in this crate more rapidly.
[profile.dev.package."*"]
opt-level = 3
