[package]
name = "penumbra-reindexer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
directories = "5.0.1"
tendermint = { version = "0.34.0", default-features = false }
tendermint-proto = "0.34"
toml = "0.8.19"

# In debug builds, nonetheless compile dependencies in release mode, for performance.
#
# The penumbra deps in particular are quit slow in debug mode, but this lets us iterate
# on the code in this crate more rapidly.
[profile.dev.package."*"]
opt-level = 3
